spring:
   datasource:
      url: jdbc:mysql://localhost:3306/testdb123
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: Root@12345
   jpa:
      hibernate.ddl-auto: update
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQLDialect
      
   application:
    name: DB-DEMO-SERVICE
